title: EBiafra
description: A non-fiction historical website exploring the history of Biafra
baseurl: ""
url: "https://tcpuffy.github.io/ebiafra"
github_username: Tcpuffy
twitter_username: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Front matter defaults
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "EBiafra Team"